
pipeline {
    agent any

    stages {
        stage('Hello') {
            steps {
                echo 'Hello World123345677'
            }
        }
        stage('Hello2') {
            steps {
                echo 'Hello World2'
            }
        }
    }
}
